### PR TITLE
Latest 14.4

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by TechStack** [comment]
Hi, I actually use my own private ci\cd server so I have no need for any github one.
Are you just wanting to use a newer version of forge for some reason?

**Comment by hannesa2** [comment]
Maybe you have no need, but it's quite useful to test any pull request.

> Are you just wanting to use a newer version of forge for some reason?

This is a pre-work to move to `1.16.1`

**Comment by hannesa2** [comment]
But maybe you now more about the magic behind mappings ? 
Please see my question https://stackoverflow.com/questions/64522203/is-there-a-maven-list-minecraft-for-available-mappings

I just prepare things for my son (and educate him programming), and I've just technical skills and no gaming-skills.

**Comment by TechStack** [comment]
yeah the mappings come from the MCP (minecraft coder pack) mappings --> http://export.mcpbot.bspk.rs/
As far as updating to a newer version Williewilus usally has good primers on what the major changes are -> here is one for 1.15 https://gist.github.com/williewillus/30d7e3f775fe93c503bddf054ef3f93e

**Comment by hannesa2** [comment]
> yeah the mappings come from the MCP (minecraft coder pack) mappings --> http://export.mcpbot.bspk.rs/

It has no `1.16` at all !
 
image

but this is working
`mappings channel: 'snapshot', version: '20200514-1.16'`

This confuses me, I'm looking for a clean **download url**, and additional to a browse-able directory, to understand what's going on here

**Comment by hannesa2** [comment]
I forced an error with 
`mappings channel: 'snapshot', version: '20200515-1.16'`, 
to have a proper error message

```
Could not download MCP Mappings: net.minecraft:mappings_snapshot:20200515-1.16@zip
Error getting artifact: net.minecraftforge:forge:1.16.1-32.0.108_mapped_snapshot_20200515-1.16:null@jar from  MinecraftUserRepo
```

I see, it tries to download from maven 
`net.minecraftforge:forge:1.16.1-32.0.108_mapped_snapshot_20200515-1.16:null@jar`

The mappings are a jar file ?
Why the null ?
Is there a way to browse it, like other maven artifactories have ?

This is the only I found http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.16.1.html
but it has no mappings folder or similar

**Comment by TechStack** [comment]
Hi @hannesa2 ,
Few topics here:
1. Updating this RTS mod to 1.15 or 1.16. Other than 1.15's rendering changes possibly having a performance increase I'm not seeing the point in updating this mod. We do not use any new features in the new versions. I'm not saying I won't update it just not clear on the reason behind it.
2. I think this is getting a bit off topic for this PR's purpose. Perhaps us discussing how to upgrade MC in a different messaging system or a different thread is better. 
3. I'm not sure what is up with the MCP website as I haven't tried to update any of my mods to 1.16 yet. That said I do know Mojang had decided recently to stop changing their obfuscation mappings so that change could have possibly  impacted how the mcp team operates.
That said when i go to update to a newer version of Minecraft & forge I go to the forge download site download the version of the MDK i want to work with and look at it's build.gradle it will tell me MCP mappings that they used. That is typically what I go with. :)

**Pull request closed without merging**
