### PR TITLE
Github CI

### PR DESCRIPTION
**Pull request by hannesa2**
... to verify each pull request

### CODE REVIEW

**Comment by hannesa2** [comment]
Here https://github.com/hannesa2/TS-RTS/pull/1 you see, how it works.

image


I guess you have to merge it first, then the action will start everytime

**Comment by TechStack** [comment]
That's how my private ci/cd works as well a commit or or into master triggers a ful build.
If you are interested in the mod you are welcome to join my discord where we discuss development. https://discord.gg/RKEkC6

**Comment by hannesa2** [comment]
Yes, there is a response !
Why using a private one, and not using a public one ?
My motivation is to test my/all pull request and this is a pre-work to move to 1.16.x, either here or in my fork

**Comment by TechStack** [comment]
I'm using a private one because it was setup before that was a thing on github. 
I also do not want every build to be public as a lot of them are intended for testing and my jenkins server is setup to integrate with my testing server and my testers can access it :)
It also cuts down on mod re-posting.

I had actually started a branch for 1.15.2 version of Minecraft but had switched back in favor of adding new content for now.
between 1.14.4 and 1.15.2 they added a lot of rendering changes and it will a decent amount of work to migrate it all.

**Comment by hannesa2** [comment]
Sorry, this chat program doesn't let me chat 

image

Without I can't chat

**Comment by TechStack** [comment]
Oh very odd. maybe you already had an account.. They probably have a password reset option if your email is already registered.

**Comment by hannesa2** [comment]
> I had actually started a branch for 1.15.2 version of Minecraft but had switched back in favor of adding new content for now.
> between 1.14.4 and 1.15.2 they added a lot of rendering changes and it will a decent amount of work to migrate it all.

Yes I observed it with the try to change to 1.16.1. 
It ends in a lot of parameter compare of obfuscated methods. That's why I search for a more recent mappings https://stackoverflow.com/questions/64522203/is-there-a-maven-list-minecraft-for-available-mappings

**Comment by TechStack** [comment]
I'm live over at https://youtu.be/JjESo8DvTCM if you want to talk about it

**Comment by hannesa2** [comment]
> I had actually started a branch for 1.15.2 version of Minecraft but had switched back in favor of adding new content for now.
> between 1.14.4 and 1.15.2 they added a lot of rendering changes and it will a decent amount of work to migrate it all.

I don't see a `1.15.x` branch, is there one ?

**Comment by hannesa2** [comment]
> I'm using a private one because it was setup before that was a thing on github.
> I also do not want every build to be public as a lot of them are intended for testing and my jenkins server is setup to integrate with my testing server and my testers can access it :)

You work with a local CI, this indicates a non-contribution-repo, It's ok, but good to know for me.
But where is the `Jenkinsfile` to control Jenkins ? What you wrote is not inconclusive for me.

A local and a public CI is not a thing witch exclude each other.

**Pull request closed without merging**
